<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>AishiKeysV2</AssemblyName>
    <RootNamespace>AishiKeysV2</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Configuration Condition="'$(Configuration)' == ''">Release</Configuration>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <Deterministic>true</Deterministic>
    <Version>1.0.4</Version>

    <SPTRoot Condition="'$(SPTRoot)' == ''">C:\SPTIV</SPTRoot>
    <ManagedPath>$(SPTRoot)\EscapeFromTarkov_Data\Managed</ManagedPath>
    <BepInExCore>$(SPTRoot)\BepInEx\core</BepInExCore>
    <BepInExPlugins>$(SPTRoot)\BepInEx\plugins</BepInExPlugins>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Fika\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCore)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ManagedPath)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCore)\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>$(ManagedPath)\Comfort.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>$(ManagedPath)\Sirenix.Serialization.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="spt-reflection">
      <HintPath>$(BepInExPlugins)\spt\spt-reflection.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ManagedPath)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedPath)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>
